# con <- idaConnect("BLUDB","","")
# idaInit(con)
# df <- idaShowTables()
# schemas <- idaQuery("Select distinct(name), ColType, Length from Sysibm.syscolumns where tbname = 'TREE_94090_1445617464_COLUMNS';")
# print(paste('"',schemas$NAME,'"',sep='',collapse=','))
# print(paste('"',schemas$COLTYPE,'"',sep='',collapse=','))
# print(paste('"',schemas$LENGTH,'"',sep='',collapse=','))
# idaClose(con)

# inputmetadata <- idaQuery("SELECT COLUMNNAME, DATATYPE, OPTYPE FROM <model_name>_COLUMNS where USAGETYPE='predicted';")
# print(paste(inputmetadata$COLUMNNAME,sep='',collapse=','))

library(ibmdbR)
mycon <- idaConnect("BLUDB","","")
idaInit(mycon)
inputmetadata <- idaQuery("SELECT COLUMNNAME, DATATYPE, OPTYPE FROM <model_name>_COLUMNS where USAGETYPE='active';")
input <- paste("{","'name':'",inputmetadata$COLUMNNAME,"'",",","'storageType':'",inputmetadata$DATATYPE,"'",",","'measurementLevel':'",inputmetadata$OPTYPE,"'","}", sep="",collapse=",")
outputmetadata <- idaQuery("SELECT COLUMNNAME, DATATYPE, OPTYPE FROM <model_name>_COLUMNS where USAGETYPE='predicted';")
output <- paste("{","'name':'",outputmetadata$COLUMNNAME,"'",",","'storageType':'",outputmetadata$DATATYPE,"'",",","'measurementLevel':'",outputmetadata$OPTYPE,"'","}", sep="",collapse=",")
cat(paste("{","'","InputMetadata","'",":","[",input,"]",",","'","OutputMetadata","'",":","[",output,"]","}", sep=""))
idaClose(mycon)