library(ibmdbR)
library(rpart.plot)
mycon <- idaConnect("BLUDB", "", "")
idaInit(mycon)
tr <- idaRetrieveModel('<modelname>')
jpeg("out.jpg",width=600,height=600)
plot(tr)
ignoreResponse <- dev.off()
idaClose(mycon)